language: node_js
node_js:
- '0.12'
git:
  depth: 10
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -qg bower gulp-cli
- npm install -q
- bower install --force
- bower install --force
script: gulp
deploy:
  provider: npm
  email: adrien.crivelli@gmail.com
  api_key:
    secure: Qus4bQOCSS9T3rDAxXKhFnDt0u0gNw/SFEzutxDG0j47h4Yyio/KcEltwRmlmW/n09re6nQXy8HxVsiZuGJs4f4v3mWaOvJ/QPKp+tPwx/qW2h5YVcmkkzO0OqeRFRfIZobn6AJ8WuWiQIe4h4JX5/8QpFFH6e+TkBjOVugJXDPhVrYp/DTkDdrDuiUSqg6Qa/t+F2K70QaxiafcyA/YFXtdMQLJLSjDS4EJMfK282OTk0Rt6k5QGkiHJASqcWQH7UWYXxTymzLAaQG0VaYzicKfnv0vev3wpv05ZpAh/QobDpfcbGTUhgQWDRZk1/y+9nkBlK2HU8vBXIYdyZPsqRsEuQ50MdAwOm7QMCdmad/2wBEEvzca2VNMrUN67HgRR5nKl34/Wretc2j/QxDObHX/NhavrZhkk5ebdz2odFh5eFy+lmic/zZPBpzSee30J5Jw3z1zRvZCSmAia9q1kawlkAxHXdUJI+pN3A6xCCJlfvxBFU4HFOuXhOyeHOXJYi37HfGUc/V7uwP0RQzb69fwYo5kdb7O03rnN6QHIIpH0DkN547JIP04hf5e+uv1agkDsFkW06wyaWnTlieBwn2W82UYs99IdfXbz1evxCEbtzd+n0ja+zB7h+65gwHOqHTwhJXwgnAu+NReCjBqWenfNV5SOWZtVfx1Nr5p5HI=
  on:
    tags: true
    repo: angular-ui/ui-uploader
